---
functional:
  - Пользователь должен иметь возможность авторизоваться через электронную
    почту, аккаунт Github, или аккаунт Discord.
  - Пользователь может создать аккаунт через Email.
  - Пользователь может добавлять способы авторизации (Github, Discord) к
    аккаунту.
  - Пользователь может изменить Nickname.
  - Пользователь может восстановить пароль в случае его потери.
  - Пользователь может менять уровень громкости и звуковое сопровождение в
    настройках.
  - Пользователь имеет личный кабинет на сайте, где отображена статистика
    активности, а также статистика игр.
  - Пользователь может играть с ботом без регистрации на сайте.
  - На сайте есть общий рейтинг всех пользователей.
  - Пользователь может выбрать уровень сложности игры.
  - Пользователь может выбрать язык программирование.
  - Пользователь может играть с ботом, с другим пользователем или с другом по
    ссылке.
  - Пользователь может выбрать продолжительность игры.
  - Пользователь может выбрать конкретное или случайное задание для игры.
  - Пользователь может присоединиться к уже созданной ботом или другим
    пользователем игре.
  - Пользователь может наблюдать за игрой в качестве зрителя.
  - Пользователь может создать турнир.
  - Пользователь может оставлять комментарии.
  - Пользователь не можит зарегистрироватся аккаунт на некорректный адрес электронной почты
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика - например
    1000 одновременных пользователей
implicit:
  - На сайте должно быть описание проекта.
  - Пользователь должен иметь возможность просматривать сайт на английском или на русском языке
  - Пользователь может изменить пароль входа в аккаунт.
  - Пользователь может изменить Email.
  - При регистрации через Email на него отправляется письмо со ссылкой для
    подтверждения Email.  

